version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment: # environment variables for the build itself
      CACHE_ENABLED: false

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - run: go build -v
      - run: go test -v

nightly:
  triggers:
    - schedule:
        cron: "0 22 * * *"
        filters:
          branches:
            only:
              - master
  jobs:
    - build