version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - run: go build -v
      - run: go test -v

